In [ ]:
# Read data (CSV) 
# Format: race1 1st, race1 2nd, race1 3rd, ...
# Races can have up to 15 choices, but can have as few as 1
# Sort by race (groupby)

In [1]:
import pandas as pd

In [95]:
df = pd.read_csv('ballot_data_2.csv')
df.drop('Timestamp', axis=1, inplace=True)
df.drop('Name', axis=1, inplace=True)
df.drop(' [Row 1]', axis=1, inplace=True)

In [96]:
df

,Senator [1st Choice],Senator [2nd Choice],Senator [3rd Choice],Governor [1st Choice],Governor [2nd Choice],Governor [3rd Choice],HB 49 [1st Choice],HB 49 [2nd Choice],HB 49 [3rd Choice],HB 49 [4th Choice],HB 49 [5th Choice],HB 49 [6th Choice]
0,Talarico,No endorsement,NaN,Gina,NaN,NaN,Hodges,Garibay,Reyna,NaN,NaN,NaN
1,Allred,Talarico,NaN,Bobby Cole,Gina,NaN,Wang,Garibay,NaN,NaN,NaN,NaN
2,Talarico,NaN,NaN,Bobby Cole,No endorsement,NaN,Wang,Reyna,NaN,NaN,NaN,NaN
3,Talarico,NaN,NaN,Gina,NaN,NaN,Garibay,Hodges,Reyna,Wang,No Endorsement,NaN
4,Talarico,NaN,NaN,Gina,NaN,NaN,Hodges,Garibay,Reyna,Wang,No Endorsement,NaN
5,Talarico,No endorsement,NaN,Gina,No endorsement,NaN,Reyna,Wang,Hodges,Garibay,No Endorsement,NaN
6,Talarico,NaN,NaN,Bobby Cole,Gina,NaN,Wang,Reyna,Hodges,Garibay,NaN,NaN
7,Talarico,NaN,NaN,Gina,NaN,NaN,Garibay,Hodges,Reyna,Wang,No Endorsement,NaN
8,Talarico,NaN,NaN,Gina,NaN,NaN,Garibay,Reyna,Wang,Hodges,NaN,NaN
9,Talarico,NaN,NaN,Bobby Cole,NaN,NaN,Garibay,Hodges,Reyna,Wang,NaN,NaN
10,Talarico,NaN,NaN,Gina,NaN,NaN,Wang,Reyna,Hodges,Garibay,NaN,NaN
11,Allred,Talarico,NaN,Gina,Bobby Cole,NaN,Reyna,Wang,Hodges,Garibay,NaN,NaN
12,Talarico,Allred,NaN,Bobby Cole,Gina,NaN,Reyna,Hodges,Wang,Garibay,NaN,NaN
13,Talarico,Allred,NaN,Bobby Cole,Gina,NaN,Reyna,Wang,Garibay,Hodges,NaN,NaN
14,Talarico,NaN,NaN,Gina,NaN,NaN,Reyna,Garibay,Hodges,Wang,NaN,NaN
15,Talarico,Allred,NaN,Gina,Bobby Cole,NaN,Hodges,Garibay,Reyna,Wang,NaN,NaN
16,Talarico,NaN,NaN,Gina,NaN,NaN,Hodges,Garibay,Reyna,Wang,NaN,NaN
17,Talarico,NaN,NaN,Bobby Cole,NaN,NaN,Wang,Reyna,Garibay,Hodges,NaN,NaN
18,Talarico,NaN,NaN,Gina,NaN,NaN,Garibay,Hodges,Reyna,Wang,NaN,NaN
19,Talarico,NaN,NaN,Bobby Cole,NaN,NaN,Garibay,Reyna,Hodges,Wang,NaN,NaN
20,Talarico,Allred,NaN,Gina,NaN,NaN,Reyna,Garibay,Wang,Hodges,NaN,NaN

In [97]:
# df.drop(' [Row 1]', axis=1, inplace=True)

In [98]:
df

,Senator [1st Choice],Senator [2nd Choice],Senator [3rd Choice],Governor [1st Choice],Governor [2nd Choice],Governor [3rd Choice],HB 49 [1st Choice],HB 49 [2nd Choice],HB 49 [3rd Choice],HB 49 [4th Choice],HB 49 [5th Choice],HB 49 [6th Choice]
0,Talarico,No endorsement,NaN,Gina,NaN,NaN,Hodges,Garibay,Reyna,NaN,NaN,NaN
1,Allred,Talarico,NaN,Bobby Cole,Gina,NaN,Wang,Garibay,NaN,NaN,NaN,NaN
2,Talarico,NaN,NaN,Bobby Cole,No endorsement,NaN,Wang,Reyna,NaN,NaN,NaN,NaN
3,Talarico,NaN,NaN,Gina,NaN,NaN,Garibay,Hodges,Reyna,Wang,No Endorsement,NaN
4,Talarico,NaN,NaN,Gina,NaN,NaN,Hodges,Garibay,Reyna,Wang,No Endorsement,NaN
5,Talarico,No endorsement,NaN,Gina,No endorsement,NaN,Reyna,Wang,Hodges,Garibay,No Endorsement,NaN
6,Talarico,NaN,NaN,Bobby Cole,Gina,NaN,Wang,Reyna,Hodges,Garibay,NaN,NaN
7,Talarico,NaN,NaN,Gina,NaN,NaN,Garibay,Hodges,Reyna,Wang,No Endorsement,NaN
8,Talarico,NaN,NaN,Gina,NaN,NaN,Garibay,Reyna,Wang,Hodges,NaN,NaN
9,Talarico,NaN,NaN,Bobby Cole,NaN,NaN,Garibay,Hodges,Reyna,Wang,NaN,NaN
10,Talarico,NaN,NaN,Gina,NaN,NaN,Wang,Reyna,Hodges,Garibay,NaN,NaN
11,Allred,Talarico,NaN,Gina,Bobby Cole,NaN,Reyna,Wang,Hodges,Garibay,NaN,NaN
12,Talarico,Allred,NaN,Bobby Cole,Gina,NaN,Reyna,Hodges,Wang,Garibay,NaN,NaN
13,Talarico,Allred,NaN,Bobby Cole,Gina,NaN,Reyna,Wang,Garibay,Hodges,NaN,NaN
14,Talarico,NaN,NaN,Gina,NaN,NaN,Reyna,Garibay,Hodges,Wang,NaN,NaN
15,Talarico,Allred,NaN,Gina,Bobby Cole,NaN,Hodges,Garibay,Reyna,Wang,NaN,NaN
16,Talarico,NaN,NaN,Gina,NaN,NaN,Hodges,Garibay,Reyna,Wang,NaN,NaN
17,Talarico,NaN,NaN,Bobby Cole,NaN,NaN,Wang,Reyna,Garibay,Hodges,NaN,NaN
18,Talarico,NaN,NaN,Gina,NaN,NaN,Garibay,Hodges,Reyna,Wang,NaN,NaN
19,Talarico,NaN,NaN,Bobby Cole,NaN,NaN,Garibay,Reyna,Hodges,Wang,NaN,NaN
20,Talarico,Allred,NaN,Gina,NaN,NaN,Reyna,Garibay,Wang,Hodges,NaN,NaN

In [99]:
# Group columns by race (everything before the opening bracket)
race_groups = {}
for col in df.columns:
    if '[' in col:
        race_name = col.split('[')[0].strip()
        if race_name not in race_groups:
            race_groups[race_name] = []
        race_groups[race_name].append(col)

# Display the groups
for race, cols in race_groups.items():
    print(f"{race}: {cols}")

Senator: ['Senator [1st Choice]', 'Senator [2nd Choice]', 'Senator [3rd Choice]']
Governor: ['Governor [1st Choice]', 'Governor [2nd Choice]', 'Governor [3rd Choice]']
HB 49: ['HB 49 [1st Choice]', 'HB 49 [2nd Choice]', 'HB 49 [3rd Choice]', 'HB 49 [4th Choice]', 'HB 49 [5th Choice]', 'HB 49 [6th Choice]']

In [100]:
races = list(race_groups.keys())
print(races)

['Senator', 'Governor', 'HB 49']

In [101]:
# Create separate DataFrames for each race
race_dfs = {}
for race_name, columns in race_groups.items():
    race_dfs[race_name] = df[columns].copy()

# Display the race names
print("Available races:", list(race_dfs.keys()))

race_dfs

Available races: ['Senator', 'Governor', 'HB 49']

{'Senator':    Senator [1st Choice] Senator [2nd Choice]  Senator [3rd Choice]
 0              Talarico       No endorsement                   NaN
 1                Allred             Talarico                   NaN
 2              Talarico                  NaN                   NaN
 3              Talarico                  NaN                   NaN
 4              Talarico                  NaN                   NaN
 5              Talarico       No endorsement                   NaN
 6              Talarico                  NaN                   NaN
 7              Talarico                  NaN                   NaN
 8              Talarico                  NaN                   NaN
 9              Talarico                  NaN                   NaN
 10             Talarico                  NaN                   NaN
 11               Allred             Talarico                   NaN
 12             Talarico               Allred                   NaN
 13             Talarico               Allred                   NaN
 14             Talarico                  NaN                   NaN
 15             Talarico               Allred                   NaN
 16             Talarico                  NaN                   NaN
 17             Talarico                  NaN                   NaN
 18             Talarico                  NaN                   NaN
 19             Talarico                  NaN                   NaN
 20             Talarico               Allred                   NaN,
 'Governor':    Governor [1st Choice] Governor [2nd Choice]  Governor [3rd Choice]
 0                   Gina                   NaN                    NaN
 1             Bobby Cole                  Gina                    NaN
 2             Bobby Cole        No endorsement                    NaN
 3                   Gina                   NaN                    NaN
 4                   Gina                   NaN                    NaN
 5                   Gina        No endorsement                    NaN
 6             Bobby Cole                  Gina                    NaN
 7                   Gina                   NaN                    NaN
 8                   Gina                   NaN                    NaN
 9             Bobby Cole                   NaN                    NaN
 10                  Gina                   NaN                    NaN
 11                  Gina            Bobby Cole                    NaN
 12            Bobby Cole                  Gina                    NaN
 13            Bobby Cole                  Gina                    NaN
 14                  Gina                   NaN                    NaN
 15                  Gina            Bobby Cole                    NaN
 16                  Gina                   NaN                    NaN
 17            Bobby Cole                   NaN                    NaN
 18                  Gina                   NaN                    NaN
 19            Bobby Cole                   NaN                    NaN
 20                  Gina                   NaN                    NaN,
 'HB 49':    HB 49 [1st Choice] HB 49 [2nd Choice] HB 49 [3rd Choice]  \
 0              Hodges            Garibay              Reyna
 1                Wang            Garibay                NaN
 2                Wang              Reyna                NaN
 3             Garibay             Hodges              Reyna
 4              Hodges            Garibay              Reyna
 5               Reyna               Wang             Hodges
 6                Wang              Reyna             Hodges
 7             Garibay             Hodges              Reyna
 8             Garibay              Reyna               Wang
 9             Garibay             Hodges              Reyna
 10               Wang              Reyna             Hodges
 11              Reyna               Wang             Hodges
 12              Reyna             Hodges               Wang
 13              Reyna               Wang            Garibay
 14              Reyna            Garibay             Hodges
 15             Hodges            Garibay              Reyna
 16             Hodges            Garibay              Reyna
 17               Wang              Reyna            Garibay
 18            Garibay             Hodges              Reyna
 19            Garibay              Reyna             Hodges
 20              Reyna            Garibay               Wang

    HB 49 [4th Choice] HB 49 [5th Choice]  HB 49 [6th Choice]
 0                 NaN                NaN                 NaN
 1                 NaN                NaN                 NaN
 2                 NaN                NaN                 NaN
 3                Wang     No Endorsement                 NaN
 4                Wang     No Endorsement                 NaN
 5             Garibay     No Endorsement                 NaN
 6             Garibay                NaN                 NaN
 7                Wang     No Endorsement                 NaN
 8              Hodges                NaN                 NaN
 9                Wang                NaN                 NaN
 10            Garibay                NaN                 NaN
 11            Garibay                NaN                 NaN
 12            Garibay                NaN                 NaN
 13             Hodges                NaN                 NaN
 14               Wang                NaN                 NaN
 15               Wang                NaN                 NaN
 16               Wang                NaN                 NaN
 17             Hodges                NaN                 NaN
 18               Wang                NaN                 NaN
 19               Wang                NaN                 NaN
 20             Hodges                NaN                 NaN  }

In [102]:
race_dfs['Senator']

   Senator [1st Choice] Senator [2nd Choice]  Senator [3rd Choice]
0              Talarico       No endorsement                   NaN
1                Allred             Talarico                   NaN
2              Talarico                  NaN                   NaN
3              Talarico                  NaN                   NaN
4              Talarico                  NaN                   NaN
5              Talarico       No endorsement                   NaN
6              Talarico                  NaN                   NaN
7              Talarico                  NaN                   NaN
8              Talarico                  NaN                   NaN
9              Talarico                  NaN                   NaN
10             Talarico                  NaN                   NaN
11               Allred             Talarico                   NaN
12             Talarico               Allred                   NaN
13             Talarico               Allred                   NaN
14             Talarico                  NaN                   NaN
15             Talarico               Allred                   NaN
16             Talarico                  NaN                   NaN
17             Talarico                  NaN                   NaN
18             Talarico                  NaN                   NaN
19             Talarico                  NaN                   NaN
20             Talarico               Allred                   NaN

In [103]:
# For each race:
# [list of races, that's one loop header]

# Make data structure for counting votes:
# Dictionary of {candidate: num votes}
# Advance: {race: {candidate: num votes}}

# Loop through each ballot 
# [list of ballots, that's the secondary loop header]
# [[stopping condition for elimination is when we have 60%, which is candidates[name] / total votes > 0.6]]
#   # Finish the current loop to get counts for each candidate
# If no > 0.6, then there is no endorsement (show which candidates have which percent, num and percent)
# No case for ties for bottom elimination
# Need to store the previous voting counts

In [110]:
race_dfs

{'Senator':    Senator [1st Choice] Senator [2nd Choice]  Senator [3rd Choice]
 0              Talarico       No endorsement                   NaN
 1                Allred             Talarico                   NaN
 2              Talarico                  NaN                   NaN
 3              Talarico                  NaN                   NaN
 4              Talarico                  NaN                   NaN
 5              Talarico       No endorsement                   NaN
 6              Talarico                  NaN                   NaN
 7              Talarico                  NaN                   NaN
 8              Talarico                  NaN                   NaN
 9              Talarico                  NaN                   NaN
 10             Talarico                  NaN                   NaN
 11               Allred             Talarico                   NaN
 12             Talarico               Allred                   NaN
 13             Talarico               Allred                   NaN
 14             Talarico                  NaN                   NaN
 15             Talarico               Allred                   NaN
 16             Talarico                  NaN                   NaN
 17             Talarico                  NaN                   NaN
 18             Talarico                  NaN                   NaN
 19             Talarico                  NaN                   NaN
 20             Talarico               Allred                   NaN,
 'Governor':    Governor [1st Choice] Governor [2nd Choice]  Governor [3rd Choice]
 0                   Gina                   NaN                    NaN
 1             Bobby Cole                  Gina                    NaN
 2             Bobby Cole        No endorsement                    NaN
 3                   Gina                   NaN                    NaN
 4                   Gina                   NaN                    NaN
 5                   Gina        No endorsement                    NaN
 6             Bobby Cole                  Gina                    NaN
 7                   Gina                   NaN                    NaN
 8                   Gina                   NaN                    NaN
 9             Bobby Cole                   NaN                    NaN
 10                  Gina                   NaN                    NaN
 11                  Gina            Bobby Cole                    NaN
 12            Bobby Cole                  Gina                    NaN
 13            Bobby Cole                  Gina                    NaN
 14                  Gina                   NaN                    NaN
 15                  Gina            Bobby Cole                    NaN
 16                  Gina                   NaN                    NaN
 17            Bobby Cole                   NaN                    NaN
 18                  Gina                   NaN                    NaN
 19            Bobby Cole                   NaN                    NaN
 20                  Gina                   NaN                    NaN,
 'HB 49':    HB 49 [1st Choice] HB 49 [2nd Choice] HB 49 [3rd Choice]  \
 0             Garibay                NaN                NaN
 1             Garibay                NaN                NaN
 2                 NaN                NaN                NaN
 3             Garibay     No Endorsement                NaN
 4             Garibay     No Endorsement                NaN
 5             Garibay     No Endorsement                NaN
 6             Garibay                NaN                NaN
 7             Garibay     No Endorsement                NaN
 8             Garibay                NaN                NaN
 9             Garibay                NaN                NaN
 10            Garibay                NaN                NaN
 11            Garibay                NaN                NaN
 12            Garibay                NaN                NaN
 13            Garibay                NaN                NaN
 14            Garibay                NaN                NaN
 15            Garibay                NaN                NaN
 16            Garibay                NaN                NaN
 17            Garibay                NaN                NaN
 18            Garibay                NaN                NaN
 19            Garibay                NaN                NaN
 20            Garibay                NaN                NaN

    HB 49 [4th Choice] HB 49 [5th Choice]  HB 49 [6th Choice]
 0                 NaN                NaN                 NaN
 1                 NaN                NaN                 NaN
 2                 NaN                NaN                 NaN
 3                 NaN                NaN                 NaN
 4                 NaN                NaN                 NaN
 5                 NaN                NaN                 NaN
 6                 NaN                NaN                 NaN
 7                 NaN                NaN                 NaN
 8                 NaN                NaN                 NaN
 9                 NaN                NaN                 NaN
 10                NaN                NaN                 NaN
 11                NaN                NaN                 NaN
 12                NaN                NaN                 NaN
 13                NaN                NaN                 NaN
 14                NaN                NaN                 NaN
 15                NaN                NaN                 NaN
 16                NaN                NaN                 NaN
 17                NaN                NaN                 NaN
 18                NaN                NaN                 NaN
 19                NaN                NaN                 NaN
 20                NaN                NaN                 NaN  }

In [ ]:
race_dfs_copy = {race: df.copy() for race, df in race_dfs.items()}

for race_name, race_df in race_dfs_copy.items():
    # print(f"Processing race: {race_name}")
    # print(race_df)
    # print()  # blank line for readability
    candidates = {}
    elimination = True

    while(elimination):
        for index, ballot in race_df.iterrows():
            # print(ballot)
            # 0) Process the ballot
            # Handled: ballot[0] = first choice

            # 1) Count first choice votes for each candidate
            if ballot[0] not in candidates and ballot[0] is not None and ballot[0] is not "nan":
                candidates[ballot[0]] = 1
            else:
                candidates[ballot[0]] += 1

            # print(candidates)

        # 2) If a candidate has > 60%, they win
        max_votes = max(candidates.values())
        if max_votes / len(race_df) > 0.6:
            winner = max(candidates, key=candidates.get)
            print(candidates)
            print(f"{winner} wins the {race_name} endorsement with {max_votes} votes ({max_votes / len(race_df) * 100:.2f}%)")
            
            elimination = False                 

        # 3) If no candidate has > 60%, eliminate the candidate with the fewest votes
        if elimination:
            min_votes = min(candidates.values())
            candidates_to_eliminate = [candidate for candidate, votes in candidates.items() if votes == min_votes]
            # Assuming no ties for elimination
            candidate_to_eliminate = candidates_to_eliminate[0]
            print(candidates)
            print(f"Eliminating {candidate_to_eliminate} with {min_votes} votes ({min_votes / len(race_df) * 100:.2f}%)")
            del candidates[candidate_to_eliminate]

            # 4) Redistribute the votes by removing the eliminated candidate from all ballots
            # and shifting remaining candidates up
            for index, ballot in race_df.iterrows():
                # Create a list of choices without the eliminated candidate
                new_ballot = [choice for choice in ballot if choice != candidate_to_eliminate]
                # Pad with None if needed to maintain the same number of columns
                while len(new_ballot) < len(ballot):
                    new_ballot.append(None)
                # Update the row in the DataFrame
                race_df.loc[index] = new_ballot
            
            # Reset candidates dictionary for next round
            # print(candidates)
            # candidates = {}

        # 5) Repeat the process until a candidate has > 60% or only two candidates remain 
        # 6) If one has 60% -> they win; if not, no endorsement
        if len(candidates) == 2 and elimination:
            print(f"No endorsement for {race_name} with candidates {list(candidates.keys())} at {candidates} votes")
            elimination = False

{'Talarico': 19, 'Allred': 2}
Talarico wins the Senator endorsement with 19 votes (90.48%)
{'Gina': 13, 'Bobby Cole': 8}
Gina wins the Governor endorsement with 13 votes (61.90%)
{'Garibay': 20, nan: 1}
Garibay wins the HB 49 endorsement with 20 votes (95.24%)

<>:17: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:17: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/var/folders/hg/k54gkq5j50lgwt6pc_hlmsph0000gn/T/ipykernel_83369/760262182.py:17: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if ballot[0] not in candidates and ballot[0] is not None and ballot[0] is not "nan":

In [108]:
# Counting process:
# 1) Count first choice votes for each candidate
# 2) If a candidate has > 60%, they win
# 3) If no candidate has > 60%, eliminate the candidate with the fewest votes
# 4) Redistribute the votes of the eliminated candidate to the next choice on those ballots
# 5) Repeat the process until a candidate has > 60% or only two candidates remain 
# 6) If one has 60% -> they win; if not, no endorsement

In [71]:
list(df.columns)

['Senator [1st Choice]',
 'Senator [2nd Choice]',
 'Senator [3rd Choice]',
 'Governor [1st Choice]',
 'Governor [2nd Choice]',
 'Governor [3rd Choice]',
 'HB 49 [1st Choice]',
 'HB 49 [2nd Choice]',
 'HB 49 [3rd Choice]',
 'HB 49 [4th Choice]',
 'HB 49 [5th Choice]',
 'HB 49 [6th Choice]']